<?php $icons = array();
$icons['stmicons']['app_bubble'] = array("class"=>'app_bubble',"tags"=>'app_bubble');
$icons['stmicons']['app_calendar'] = array("class"=>'app_calendar',"tags"=>'app_calendar');
$icons['stmicons']['app_email'] = array("class"=>'app_email',"tags"=>'app_email');
$icons['stmicons']['app_eye'] = array("class"=>'app_eye',"tags"=>'app_eye');
$icons['stmicons']['app_hand'] = array("class"=>'app_hand',"tags"=>'app_hand');
$icons['stmicons']['app_learning'] = array("class"=>'app_learning',"tags"=>'app_learning');
$icons['stmicons']['app_like'] = array("class"=>'app_like',"tags"=>'app_like');
$icons['stmicons']['app_pen'] = array("class"=>'app_pen',"tags"=>'app_pen');
$icons['stmicons']['app_pin'] = array("class"=>'app_pin',"tags"=>'app_pin');
$icons['stmicons']['app_sound'] = array("class"=>'app_sound',"tags"=>'app_sound');
$icons['stmicons']['app_user'] = array("class"=>'app_user',"tags"=>'app_user');