<?php $icons = array();
$icons['stmicons']['renovation_shield'] = array("class"=>'renovation_shield',"tags"=>'renovation_shield');
$icons['stmicons']['renovation_diamond'] = array("class"=>'renovation_diamond',"tags"=>'renovation_diamond');
$icons['stmicons']['renovation_drill'] = array("class"=>'renovation_drill',"tags"=>'renovation_drill');
$icons['stmicons']['renovation_cup'] = array("class"=>'renovation_cup',"tags"=>'renovation_cup');
$icons['stmicons']['renovation_worker'] = array("class"=>'renovation_worker',"tags"=>'renovation_worker');
$icons['stmicons']['renovation_checklist'] = array("class"=>'renovation_checklist',"tags"=>'renovation_checklist');
$icons['stmicons']['renovation_customers'] = array("class"=>'renovation_customers',"tags"=>'renovation_customers');
$icons['stmicons']['renovation_carpentry'] = array("class"=>'renovation_carpentry',"tags"=>'renovation_carpentry');
$icons['stmicons']['renovation_electrical'] = array("class"=>'renovation_electrical',"tags"=>'renovation_electrical');
$icons['stmicons']['renovation_gears'] = array("class"=>'renovation_gears',"tags"=>'renovation_gears');
$icons['stmicons']['renovation_maintenance'] = array("class"=>'renovation_maintenance',"tags"=>'renovation_maintenance');
$icons['stmicons']['renovation_painting'] = array("class"=>'renovation_painting',"tags"=>'renovation_painting');
$icons['stmicons']['renovation_plumbing'] = array("class"=>'renovation_plumbing',"tags"=>'renovation_plumbing');
$icons['stmicons']['arrow_forward'] = array("class"=>'arrow_forward',"tags"=>'arrow_forward');