<?php $icons = array();
$icons['stmicons']['pearl-politician_arrow_left'] = array("class"=>'pearl-politician_arrow_left',"tags"=>'pearl-politician_arrow_left');
$icons['stmicons']['pearl-politician_briefcase'] = array("class"=>'pearl-politician_briefcase',"tags"=>'pearl-politician_briefcase');
$icons['stmicons']['pearl-politician_calendar'] = array("class"=>'pearl-politician_calendar',"tags"=>'pearl-politician_calendar');
$icons['stmicons']['pearl-politician_chair'] = array("class"=>'pearl-politician_chair',"tags"=>'pearl-politician_chair');
$icons['stmicons']['pearl-politician_coins'] = array("class"=>'pearl-politician_coins',"tags"=>'pearl-politician_coins');
$icons['stmicons']['pearl-politician_envelope'] = array("class"=>'pearl-politician_envelope',"tags"=>'pearl-politician_envelope');
$icons['stmicons']['pearl-politician_medical'] = array("class"=>'pearl-politician_medical',"tags"=>'pearl-politician_medical');
$icons['stmicons']['pearl-politician_safety'] = array("class"=>'pearl-politician_safety',"tags"=>'pearl-politician_safety');
$icons['stmicons']['pearl-politician_scheudle'] = array("class"=>'pearl-politician_scheudle',"tags"=>'pearl-politician_scheudle');
$icons['stmicons']['pearl-politician_zip_code'] = array("class"=>'pearl-politician_zip_code',"tags"=>'pearl-politician_zip_code');