<?php $icons = array();
$icons['stmicons']['church-angel'] = array("class"=>'church-angel',"tags"=>'church-angel');
$icons['stmicons']['church-ask-question'] = array("class"=>'church-ask-question',"tags"=>'church-ask-question');
$icons['stmicons']['church-audio'] = array("class"=>'church-audio',"tags"=>'church-audio');
$icons['stmicons']['church-calendar'] = array("class"=>'church-calendar',"tags"=>'church-calendar');
$icons['stmicons']['church-calendar-flower'] = array("class"=>'church-calendar-flower',"tags"=>'church-calendar-flower');
$icons['stmicons']['church-chevron-right'] = array("class"=>'church-chevron-right',"tags"=>'church-chevron-right');
$icons['stmicons']['church-document'] = array("class"=>'church-document',"tags"=>'church-document');
$icons['stmicons']['church-donation'] = array("class"=>'church-donation',"tags"=>'church-donation');
$icons['stmicons']['church-download'] = array("class"=>'church-download',"tags"=>'church-download');
$icons['stmicons']['church-envelope'] = array("class"=>'church-envelope',"tags"=>'church-envelope');
$icons['stmicons']['church-hand-flower'] = array("class"=>'church-hand-flower',"tags"=>'church-hand-flower');
$icons['stmicons']['church-hands-flower'] = array("class"=>'church-hands-flower',"tags"=>'church-hands-flower');
$icons['stmicons']['church-map-pin'] = array("class"=>'church-map-pin',"tags"=>'church-map-pin');
$icons['stmicons']['church-peoples'] = array("class"=>'church-peoples',"tags"=>'church-peoples');
$icons['stmicons']['church-phone'] = array("class"=>'church-phone',"tags"=>'church-phone');
$icons['stmicons']['church-video'] = array("class"=>'church-video',"tags"=>'church-video');