<?php $icons = array();
$icons['stmicons']['furniture_arrow_right'] = array("class"=>'furniture_arrow_right',"tags"=>'furniture_arrow_right');
$icons['stmicons']['furniture_phone'] = array("class"=>'furniture_phone',"tags"=>'furniture_phone');
$icons['stmicons']['furniture_eco'] = array("class"=>'furniture_eco',"tags"=>'furniture_eco');
$icons['stmicons']['furniture_truck'] = array("class"=>'furniture_truck',"tags"=>'furniture_truck');
$icons['stmicons']['furniture_pencil'] = array("class"=>'furniture_pencil',"tags"=>'furniture_pencil');
$icons['stmicons']['furniture_like'] = array("class"=>'furniture_like',"tags"=>'furniture_like');
$icons['stmicons']['furniture_master'] = array("class"=>'furniture_master',"tags"=>'furniture_master');
$icons['stmicons']['furniture_diamond'] = array("class"=>'furniture_diamond',"tags"=>'furniture_diamond');
$icons['stmicons']['navigate_next'] = array("class"=>'navigate_next',"tags"=>'navigate_next');