<?php $icons = array();
$icons['stmicons']['database'] = array("class"=>'database',"tags"=>'database');
$icons['stmicons']['flash'] = array("class"=>'flash',"tags"=>'flash');
$icons['stmicons']['folder'] = array("class"=>'folder',"tags"=>'folder');
$icons['stmicons']['internet'] = array("class"=>'internet',"tags"=>'internet');
$icons['stmicons']['storage'] = array("class"=>'storage',"tags"=>'server-1');
$icons['stmicons']['server-1'] = array("class"=>'server-1',"tags"=>'server-3');
$icons['stmicons']['server-2'] = array("class"=>'server-2',"tags"=>'server-icon');
$icons['stmicons']['shopping-cart'] = array("class"=>'shopping-cart',"tags"=>'shopping-cart');
$icons['stmicons']['wp-logo'] = array("class"=>'wp-logo',"tags"=>'wordpress-logo');
$icons['stmicons']['www'] = array("class"=>'www',"tags"=>'www');