<?php $icons = array();
$icons['stmicons']['consulting_comment'] = array("class"=>'consulting_comment',"tags"=>'consulting_comment');
$icons['stmicons']['consulting_comment2'] = array("class"=>'consulting_comment2',"tags"=>'consulting_comment2');
$icons['stmicons']['consulting_comments'] = array("class"=>'consulting_comments',"tags"=>'consulting_comments');
$icons['stmicons']['consulting_notepad'] = array("class"=>'consulting_notepad',"tags"=>'consulting_notepad');
$icons['stmicons']['consulting_pin'] = array("class"=>'consulting_pin',"tags"=>'consulting_pin');
$icons['stmicons']['consulting_rocket'] = array("class"=>'consulting_rocket',"tags"=>'consulting_rocket');
$icons['stmicons']['consulting_schedule'] = array("class"=>'consulting_schedule',"tags"=>'consulting_schedule');
$icons['stmicons']['consulting_schedule2'] = array("class"=>'consulting_schedule2',"tags"=>'consulting_schedule2');
$icons['stmicons']['consulting_scholar'] = array("class"=>'consulting_scholar',"tags"=>'consulting_scholar');
$icons['stmicons']['consulting_settings'] = array("class"=>'consulting_settings',"tags"=>'consulting_settings');
$icons['stmicons']['consulting_specialist'] = array("class"=>'consulting_specialist',"tags"=>'consulting_specialist');
$icons['stmicons']['consulting_target'] = array("class"=>'consulting_target',"tags"=>'consulting_target');
$icons['stmicons']['consulting_views'] = array("class"=>'consulting_views',"tags"=>'consulting_views');
$icons['stmicons']['consulting_quote'] = array("class"=>'consulting_quote',"tags"=>'consulting_quote');