<?php
    // Single + Container Elements
    // ---------------------------
    $this->TS_VCSC_Visual_Composer_Groups = array(
        "Media"                                     => array("title" => __('Media', 'ts_visual_composer_extend'),                   "class" => "ts-composium-media"),
        "Google"                                    => array("title" => __('Google', 'ts_visual_composer_extend'),                  "class" => "ts-composium-google"),
        "Buttons"                                   => array("title" => __('Buttons + Links', 'ts_visual_composer_extend'),         "class" => "ts-composium-buttons"),
        "Counters"                                  => array("title" => __('Countdown + Counters', 'ts_visual_composer_extend'),    "class" => "ts-composium-counters"),
        "Posts"                                     => array("title" => __('Posts + Pages', 'ts_visual_composer_extend'),           "class" => "ts-composium-posts"),
        "Titles"                                    => array("title" => __('Titles', 'ts_visual_composer_extend'),                  "class" => "ts-composium-titles"),
        "Popups"                                    => array("title" => __('Modals + Popups', 'ts_visual_composer_extend'),         "class" => "ts-composium-popups"),
        "Post Types"                                => array("title" => __('Custom Post Types', 'ts_visual_composer_extend'),       "class" => "ts-composium-types"),
        "Timelines"                                 => array("title" => __('Time + Process Lines', 'ts_visual_composer_extend'),    "class" => "ts-composium-timelines"),
        "Other"                                     => array("title" => __('Other / Various', 'ts_visual_composer_extend'),         "class" => "ts-composium-other"),
        "BETA"                                      => array("title" => __('BETA', 'ts_visual_composer_extend'),                    "class" => "ts-composium-beta"),
        "Extra"                                     => array("title" => __('Extras / Specials', 'ts_visual_composer_extend'),       "class" => "ts-composium-extras"),
        "Demos"                                     => array("title" => __('Developers', 'ts_visual_composer_extend'),              "class" => "ts-composium-demos"),
        "Plugins"                                   => array("title" => __('3rd Party Plugins', 'ts_visual_composer_extend'),       "class" => "ts-composium-plugins"),
    );
    
    $this->TS_VCSC_Visual_Composer_Elements = array(
        // Media Elements
        "TS Image Adipoli"						    => array("setting" => "ImageAdipoli",           "base" => "TS-VCSC-Image-Adipoli",                  "file" => "image_adipoli",              "group" => "Media",         "type" => "internal",		"default" => "true",		"active" => "true",		"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "1.0.0",    "retired" => "",    "tags" => "",         "link" => "http://www.composium.krautcoding.com/image-adipoli/"),
        "TS Image Picstrips"					    => array("setting" => "ImagePicstrips",         "base" => "TS-VCSC-Image-Picstrips",                "file" => "image_picstrips",            "group" => "Media",         "type" => "internal",		"default" => "true",		"active" => "true",		"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "1.1.0",    "retired" => "",    "tags" => "",                 "link" => "http://www.composium.krautcoding.com/image-picstrips/"),
        "TS Image Caman"						    => array("setting" => "ImageCaman",             "base" => "TS-VCSC-Image-Caman",                    "file" => "image_caman",                "group" => "Media",         "type" => "internal",		"default" => "true",		"active" => "true",		"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "1.1.0",    "retired" => "",    "tags" => "",                 "link" => "http://www.composium.krautcoding.com/image-caman/"),
        "TS Image Magnify"						    => array("setting" => "ImageMagnify",           "base" => "TS_VCSC_Image_Magnify",                  "file" => "image_magnify",              "group" => "Media",         "type" => "class",		    "default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "3.0.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/image-magnify/"),
        "TS Image Switch"						    => array("setting" => "ImageSwitch",            "base" => "TS-VCSC-Image-Switch",                   "file" => "image_switch",               "group" => "Media",         "type" => "internal",		"default" => "true",		"active" => "true",		"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "1.0.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/image-switch/"),
        "TS Image Scroll"						    => array("setting" => "ImageScroll",            "base" => "TS_VCSC_Image_Scroll",                   "file" => "image_scroll",               "group" => "Media",         "type" => "internal",		"default" => "true",		"active" => "true",		"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "4.0.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/image-scroll/"),
        "TS Image 3D TiltFX"						=> array("setting" => "ImageTiltFX",            "base" => "TS_VCSC_Image_TiltFX",                   "file" => "image_tiltfx",               "group" => "Media",         "type" => "internal",		"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "4.3.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/image-3d-tiltfx/"),
        "TS Image SVG Overlay"                      => array("setting" => "ImageSVG",               "base" => "TS_VCSC_Image_SVG",                      "file" => "image_svg",                  "group" => "Media",         "type" => "internal",		"default" => "true",		"active" => "true",		"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "2.7.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/image-svg-overlay/"),
        "TS Image GIF Player"                       => array("setting" => "ImageGIF",               "base" => "TS_VCSC_Image_GIFPlayer",                "file" => "image_gifplayer",            "group" => "Media",         "type" => "class",		    "default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "5.1.2",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/image-gif-player/"),
        "TS Image Full Width"                       => array("setting" => "ImageFull",        	    "base" => "TS_VCSC_Image_Full",                     "file" => "image_full",                 "group" => "Media",         "type" => "internal",		"default" => "true",		"active" => "true",		"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "2.3.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/image-full-width/"),
        "TS Image Hotspot"					        => array("setting" => "ImageHotspot",           "base" => "TS_VCSC_Image_Hotspot_Container",        "file" => "image_hotspot",              "group" => "Media",         "type" => "class",		    "default" => "true",		"active" => "true",		"deprecated" => "false",        "required" => "4.3.0",  "children" => "0",      "introduced" => "2.6.4",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/image-hotspots/"),
        "TS Image Basic Overlay"				    => array("setting" => "ImageOverlay",           "base" => "TS-VCSC-Image-Overlay",                  "file" => "image_overlay",              "group" => "Media",         "type" => "internal",		"default" => "true",		"active" => "true",		"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "1.0.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/image-basic-overlay/"),
        "TS Image Advanced Overlay"				    => array("setting" => "ImageEffects",           "base" => "TS_VCSC_Image_Hover_Effects",            "file" => "image_hovereffects",         "group" => "Media",         "type" => "class",		    "default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "2.7.1",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/image-advanced-overlay-general/"),
        "TS Image iHover"					        => array("setting" => "ImageIHover",            "base" => "TS_VCSC_Image_IHover",                   "file" => "image_ihover",               "group" => "Media",         "type" => "class",		    "default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "2.6.4",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/image-ihover-general/"),
        "TS Image Link Grid"					    => array("setting" => "ImageGrid",              "base" => "TS_VCSC_Image_Link_Grid",                "file" => "image_grid",                 "group" => "Media",         "type" => "internal",       "default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "3.0.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/image-link-grid/"),        
        "TS Image Placeholder"					    => array("setting" => "ImagePlaceholder",       "base" => "TS_VCSC_Image_Placeholder",              "file" => "image_placeholder",          "group" => "Media",         "type" => "internal",       "default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "4.1.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/image-placeholder/"),
        "TS Image Lightbox"						    => array("setting" => "LightboxImage",          "base" => "TS-VCSC-Lightbox-Image",                 "file" => "lightbox_image",             "group" => "Media",         "type" => "internal",		"default" => "true",		"active" => "true",		"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "1.0.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/image-lightboxes/"),
        "TS Image Gallery"					        => array("setting" => "LightboxGallery",        "base" => "TS_VCSC_Lightbox_Gallery",               "file" => "lightbox_gallery",           "group" => "Media",         "type" => "class",			"default" => "true",		"active" => "true",		"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "2.3.0",    "retired" => "",    "tags" => "",   "link" => ""),
        "TS Page Background"                        => array("setting" => "PageBackground",         "base" => "TS_VCSC_Page_Background",                "file" => "page_background",            "group" => "Media",         "type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "3.0.0",    "retired" => "",    "tags" => "",   "link" => ""),
        "TS Plyr Video Player"                      => array("setting" => "PlyrPlayer",             "base" => "TS_VCSC_Plyr_Player",                    "file" => "plyrvideo",                  "group" => "Media",         "type" => "class",		    "default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "5.1.2",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/video-plyr-player/"),
        "TS Video DailyMotion"					    => array("setting" => "DailyMotion",            "base" => "TS-VCSC-Motion",                         "file" => "dailymotion",                "group" => "Media",         "type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "1.0.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/video-dailymotion/"),
        "TS Video Vimeo"						    => array("setting" => "Vimeo",                  "base" => "TS-VCSC-Vimeo",                          "file" => "vimeo",                      "group" => "Media",         "type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "1.0.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/video-vimeo/"),
        "TS Video YouTube"						    => array("setting" => "YouTube",                "base" => "TS-VCSC-Youtube",                        "file" => "youtube",                    "group" => "Media",         "type" => "internal",		"default" => "true",		"active" => "true",		"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "1.0.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/video-youtube/"),        
        "TS Video Facebook"						    => array("setting" => "FacebookVideo",          "base" => "TS_VCSC_Facebook_Video",                 "file" => "facebookvideo",              "group" => "Media",         "type" => "internal",		"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "5.1.1",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/video-facebook/"),
        "TS Projekktor Video"					    => array("setting" => "HTML5Video",             "base" => "TS_VCSC_HTML5_Video",                    "file" => "projekktor_video",           "group" => "Media",         "type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "2.6.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/video-projekktor/"),
        "TS Projekktor Audio"					    => array("setting" => "HTML5Audio",             "base" => "TS_VCSC_HTML5_Audio",                    "file" => "projekktor_audio",           "group" => "Media",         "type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "2.6.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/audio-projekktor/"),
        "TS Soundcloud Player"                      => array("setting" => "Soundcloud",             "base" => "TS_VCSC_Soundcloud",                     "file" => "soundcloud",                 "group" => "Media",         "type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "2.7.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/audio-soundcloud/"),
        "TS Mixcloud Player"                        => array("setting" => "Mixcloud",               "base" => "TS_VCSC_Mixcloud",                       "file" => "mixcloud",                   "group" => "Media",         "type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "4.0.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/audio-mixcloud/"),
        "TS MP3 Player"					            => array("setting" => "MP3Player",              "base" => "TS_VCSC_MP3_Player",                     "file" => "mp3player",                  "group" => "Media",         "type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "2.6.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/audio-mp3-player/"),
        // Google Elements
        "TS Google Charts"						    => array("setting" => "GoogleCharts",           "base" => "TS-VCSC-Google-Charts",                  "file" => "google_charts",              "group" => "Google",     	"type" => "internal",		"default" => "false",       "active" => "false",	"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "1.0.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/google-elements/google-charts/"),
        "TS Google Tables"						    => array("setting" => "GoogleTables",           "base" => "TS-VCSC-Google-Tables",                  "file" => "google_tables",              "group" => "Google",     	"type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "3.3.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/google-elements/google-tables/"),
        "TS Google Maps PLUS"			            => array("setting" => "GoogleMapsPlus",         "base" => "TS_VCSC_GoogleMapsPlus_Container",       "file" => "google_mapsplus",            "group" => "Google",       	"type" => "class",		    "default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "4.6.0",  "children" => "0",      "introduced" => "4.0.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/google-elements/google-maps-plus/"),
        "TS Google Docs"						    => array("setting" => "GoogleDocs",             "base" => "TS-VCSC-Google-Docs",                    "file" => "google_docs",                "group" => "Google",       	"type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "1.0.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/google-elements/google-documents/"),
        "TS Google Trends"						    => array("setting" => "GoogleTrends",           "base" => "TS-VCSC-Google-Trends",                  "file" => "google_trends",              "group" => "Google",     	"type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "1.0.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/google-elements/google-trends/"),        
        "TS Google Forms"						    => array("setting" => "GoogleForms",            "base" => "TS-VCSC-Google-Forms",                   "file" => "google_forms",               "group" => "Google",     	"type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "3.4.0",    "retired" => "",    "tags" => "",   "link" => ""),
        // Button + Link Elements
        "TS Icon 3D Button"						    => array("setting" => "IconButton",             "base" => "TS_VCSC_Icon_Button",                    "file" => "icon_button",                "group" => "Buttons",       "type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "2.3.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/icon-3d-buttons/"),
        "TS Icon Flex Button"					    => array("setting" => "IconFlexButton",         "base" => "TS_VCSC_Icon_Flex_Button",               "file" => "icon_flexbutton",            "group" => "Buttons",       "type" => "internal",		"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "4.3.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/icon-flex-buttons/"),
        "TS Icon Flat Button"					    => array("setting" => "IconFlatButton",         "base" => "TS_VCSC_Icon_Flat_Button",               "file" => "icon_flatbutton",            "group" => "Buttons",       "type" => "internal",		"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "3.0.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/icon-flat-buttons/"),
        "TS Icon Dual Button"					    => array("setting" => "IconDualutton",          "base" => "TS_VCSC_Icon_Dual_Button",               "file" => "icon_dualbutton",            "group" => "Buttons",       "type" => "internal",		"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "3.0.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/icon-dual-buttons/"),
        ///"TS Icon Wings Button"					=> array("setting" => "IconWingsButton",        "base" => "TS_VCSC_Icon_Wings_Button",              "file" => "icon_wingsbutton",           "group" => "Buttons",       "type" => "internal",		"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "5.1.1",    "retired" => "",    "tags" => "",   "link" => ""),
        "TS Creative Link"					        => array("setting" => "CreativeLink",           "base" => "TS_VCSC_Creative_Link",                  "file" => "creativelink",               "group" => "Buttons",       "type" => "internal",		"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "3.3.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/creative-links/"),
        "TS Figure Navigation"					    => array("setting" => "FigureNavigation",       "base" => "TS_VCSC_Figure_Navigation_Container",    "file" => "figure_navigation",          "group" => "Buttons",       "type" => "class",			"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "2.6.5",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/figure-navigation/"),        
        // Counter Elements
        "TS Counter Icon"						    => array("setting" => "IconCounter",            "base" => "TS-VCSC-Icon-Counter",                   "file" => "icon_counter",      			"group" => "Counters",      "type" => "internal",		"default" => "true",		"active" => "true",		"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "1.0.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/counter-elements/icon-counter/"),
        "TS Counter Circle"						    => array("setting" => "CircleCounter",          "base" => "TS-VCSC-Circliful",                      "file" => "circliful",         			"group" => "Counters",      "type" => "internal",		"default" => "true",		"active" => "true",		"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "2.0.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/counter-elements/circle-icon-counter/"),
        "TS Countdown"							    => array("setting" => "Countdown",              "base" => "TS-VCSC-Countdown",                      "file" => "countdown",         			"group" => "Counters",      "type" => "class",		    "default" => "true",		"active" => "true",		"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "2.0.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/counter-elements/countdown-timer/"),
        "TS Wave Gauge"						        => array("setting" => "WaveGauge",              "base" => "TS_VCSC_Wave_Gauge",                     "file" => "wavegauge",                  "group" => "Counters",      "type" => "internal",		"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "4.3.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/counter-elements/liquid-wave-counter/"),        
        "TS Counter Odometer"                       => array("setting" => "OdometerCounter",        "base" => "TS_VCSC_Counter_Odometer",               "file" => "icon_odometer",              "group" => "Counters",      "type" => "internal",		"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "5.1.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/counter-elements/odometer-counter/"),      
        // Post Type Elements
        "TS Posts Isotope Grid"					    => array("setting" => "Postsgrid",        	    "base" => "TS_VCSC_Posts_Grid_Standalone",          "file" => "postsgrid",                  "group" => "Posts",         "type" => "class",			"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "2.4.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/isotope-posts/"),
        "TS Posts Image Grid"					    => array("setting" => "Postsimage",        	    "base" => "TS_VCSC_Posts_Image_Grid_Standalone",    "file" => "postsimage",                 "group" => "Posts",         "type" => "class",			"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "3.0.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/image-posts-rectangle-grid/"),
        "TS Posts Slider"					        => array("setting" => "Postsslider",        	"base" => "TS_VCSC_Posts_Slider_Standalone",        "file" => "postsslider",                "group" => "Posts",         "type" => "class",			"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "2.6.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/posts-slider/"),
        "TS Posts Ticker"					        => array("setting" => "Poststicker",        	"base" => "TS_VCSC_Posts_Ticker_Standalone",        "file" => "poststicker",                "group" => "Posts",         "type" => "class",			"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "2.6.3",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/posts-ticker/"),        
        "TS Posts Timeline"					        => array("setting" => "Poststimeline",        	"base" => "TS_VCSC_Posts_Timeline_Standalone",      "file" => "poststimeline",              "group" => "Posts",         "type" => "class",			"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "4.0.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/posts-timeline/"),        
        // Title + Teaser Elements
        "TS Title Advanced"							=> array("setting" => "IconTitle",              "base" => "TS-VCSC-Icon-Title",                     "file" => "icon_title",                 "group" => "Titles",        "type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "1.0.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/title-icon-advanced/"),
        "TS Title Typed"						    => array("setting" => "TitleTyped",             "base" => "TS_VCSC_Title_Typed",                    "file" => "title_typed",                "group" => "Titles",        "type" => "internal",		"default" => "true",		"active" => "true",		"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "2.6.6",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/title-typed-animation/"),
        "TS Title Morphed"						    => array("setting" => "TitleMorphed",           "base" => "TS_VCSC_Title_Morphed",                  "file" => "title_morphed",              "group" => "Titles",        "type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "5.0.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/title-morphed-animations/"),        
        "TS Title Textillate"					    => array("setting" => "Textillate",             "base" => "TS-VCSC-Textillate",                     "file" => "textillate",                 "group" => "Titles",        "type" => "internal",		"default" => "true",		"active" => "true",		"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "2.2.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/textillate-animations/"),
        "TS Title Flipboard"					    => array("setting" => "Flipboard",              "base" => "TS_VCSC_Title_Flipboard",                "file" => "title_flipboard",            "group" => "Titles",        "type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "3.0.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/title-flipboard-animations/"),
        "TS Teaser Block"						    => array("setting" => "TeaserBlock",            "base" => "TS_VCSC_Teaser_Block_Standalone",        "file" => "teaser_block",      			"group" => "Titles",        "type" => "class",			"default" => "true",		"active" => "true",		"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "2.3.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/teaser-blocks/"),
        // Popup + Modal Elements
        "TS Modal Popup"						    => array("setting" => "ModalPopup",             "base" => "TS-VCSC-Modal-Popup",                    "file" => "modal",                      "group" => "Popups",        "type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "1.3.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/modal-popup/"),
        "TS Amaran Popup"						    => array("setting" => "AmaranPopup",            "base" => "TS_VCSC_Amaran_Popup",                   "file" => "amaran",                     "group" => "Popups",        "type" => "internal",		"default" => "true",		"active" => "true",		"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "2.7.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/amaran-popup/"),
        "TS Element Focus"					        => array("setting" => "ElementFocus",    		"base" => "TS_VCSC_Element_Focus",                  "file" => "element_focus",  			"group" => "Popups",        "type" => "class",			"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "3.2.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/element-focus/"),
        // Processes & Timeline Elements
        "TS Circle Steps"                           => array("setting" => "CircleSteps",            "base" => "TS_VCSC_Circle_Steps_Container",         "file" => "circle_steps",               "group" => "Timelines",     "type" => "class",			"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "4.0.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/circle-steps/"),        
        "TS CSS Media Timeline"                     => array("setting" => "MediaTimeline",          "base" => "TS_VCSC_Timeline_CSS_Container",         "file" => "timeline_css",               "group" => "Timelines",     "type" => "class",			"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "3.1.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/css-media-timeline/"),
        "TS Horizontal Timeline"                    => array("setting" => "HorizontalTimeline",     "base" => "TS_VCSC_Timeline_Horizontal_Container",  "file" => "timeline_horizontal",        "group" => "Timelines",     "type" => "class",			"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "5.1.2",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/horizontal-timeline/"),
        "TS Horizontal Steps"		                => array("setting" => "HorizontalSteps",        "base" => "TS_VCSC_Horizontal_Steps_Container",     "file" => "horizontal_steps",           "group" => "Timelines",     "type" => "class",			"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "1.0.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/horizontal-steps/"),
        "TS Process Lines"                          => array("setting" => "ProcessLines",           "base" => "TS_VCSC_ProcessLines_Container",         "file" => "processlines",               "group" => "Timelines",     "type" => "class",		    "default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "5.0.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/process-lines/"),        
        // Various (Other) Elements        
        "TS Advanced Textblock"                     => array("setting" => "TextBlock",    		    "base" => "TS_VCSC_Advanced_Textblock",             "file" => "textblock",  			    "group" => "Other",         "type" => "class",			"default" => "true",		"active" => "true",	    "deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "4.3.0",    "retired" => "",    "tags" => "",   "link" => ""),
        "TS Icon Fonts"							    => array("setting" => "FontIcons",              "base" => "TS-VCSC-Font-Icons",                     "file" => "fonticon",              		"group" => "Other",         "type" => "class",		    "default" => "true",		"active" => "true",	    "deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "1.0.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/simple-font-icons/"),
        "TS Icon Text Box"							=> array("setting" => "IconBox",                "base" => "TS-VCSC-Icon-Box-Tiny",                  "file" => "icon_box_tiny",     			"group" => "Other",         "type" => "internal",		"default" => "true",		"active" => "true",		"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "1.0.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/icon-text-boxes/"),
        "TS Icon List Item"						    => array("setting" => "IconList",               "base" => "TS-VCSC-Icon-List",                      "file" => "icon_listitem",     			"group" => "Other",         "type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "1.2.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/icon-list-items/"),        
        "TS Icon Info Box"                          => array("setting" => "IconInfo",               "base" => "TS_VCSC_Icon_Info_Box",                  "file" => "icon_infobox",     			"group" => "Other",         "type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "5.0.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/icon-info-boxes/"),        
        "TS Info / Notice Panel"                    => array("setting" => "InfoNotice",             "base" => "TS_VCSC_Info_Notice",                    "file" => "info_notice",                "group" => "Other",         "type" => "internal",		"default" => "true",		"active" => "true",		"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "2.7.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/info-notice-panels/"),
        "TS Panel Flip"                             => array("setting" => "PanelFlip",              "base" => "TS_VCSC_Panel_Flip",                     "file" => "panel_flip",                 "group" => "Other",         "type" => "internal",		"default" => "true",		"active" => "true",     "deprecated" => "false",         "required" => "",       "children" => "0",      "introduced" => "5.1.0",   "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/content-flip-box/"),
        "TS Quick Skillset"						    => array("setting" => "QuickSkills",            "base" => "TS_VCSC_Quick_Skills",                   "file" => "quick_skills",     			"group" => "Other",         "type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "4.4.0",  "children" => "0",      "introduced" => "4.0.0",    "retired" => "",    "tags" => "",   "link" => ""),
        "TS Quick Testimonial"						=> array("setting" => "QuickTestimonial",       "base" => "TS_VCSC_Quick_Testimonial",              "file" => "quick_testimonial",          "group" => "Other",         "type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "4.0.0",    "retired" => "",    "tags" => "",   "link" => ""),
        "TS Basic Pricing Table"                    => array("setting" => "PricingTable",           "base" => "TS-VCSC-Pricing-Table",                  "file" => "pricing_table",     			"group" => "Other",         "type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "1.0.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/pricing-tables-basic/"),
        "TS Inspired Pricing Table"                 => array("setting" => "PricingInspired",        "base" => "TS_VCSC_InspiredPricing_Container",      "file" => "pricing_inspired",           "group" => "Other",         "type" => "class",		    "default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "4.3.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/pricing-tables-inspired/"),
        "TS Social Networks"					    => array("setting" => "SocialNetworks",         "base" => "TS-VCSC-Social-Icons",                   "file" => "social_networks",   			"group" => "Other",         "type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "1.0.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/social-networks/"),
        "TS Divider"							    => array("setting" => "Divider",                "base" => "TS-VCSC-Divider",                        "file" => "divider",           			"group" => "Other",         "type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "1.0.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/dividers/"),
        "TS Shortcode"							    => array("setting" => "Shortcode",              "base" => "TS-VCSC-Shortcode",                      "file" => "shortcode",         			"group" => "Other",         "type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "2.0.0",    "retired" => "",    "tags" => "",   "link" => ""),        
        "TS Rating Scales"						    => array("setting" => "StarRating",             "base" => "TS_VCSC_Star_Rating",                    "file" => "seostars",         			"group" => "Other",         "type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "2.6.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/rating-scales/"),
        "TS QR-Code"							    => array("setting" => "QRCode",                 "base" => "TS-VCSC-QRCode",                         "file" => "qrcode",            			"group" => "Other",         "type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "2.0.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/qr-code-blocks/"),
        "TS Fancy List"							    => array("setting" => "FancyList",              "base" => "TS_VCSC_Fancy_List",                     "file" => "fancylist",            		"group" => "Other",         "type" => "internal",		"default" => "true",		"active" => "true",	    "deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "3.1.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/fancy-lists/"),
        "TS iPresenter"					            => array("setting" => "iPresenter",    		    "base" => "TS_VCSC_iPresenter_Container",           "file" => "ipresenter",  				"group" => "Other",         "type" => "class",			"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "2.7.2",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/ipresenter/"),        
        "TS SlitSlider"					            => array("setting" => "SlitSlider",    		    "base" => "TS_VCSC_SlitSlider_Container",           "file" => "slitslider",  				"group" => "Other",         "type" => "class",			"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "3.4.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/slitslider/"),
        "TS IFrame Embed"						    => array("setting" => "IFrame",                 "base" => "TS-VCSC-IFrame",                         "file" => "iframe",            			"group" => "Other",         "type" => "internal",		"default" => "true",		"active" => "true",		"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "1.0.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/embed-iframe/"),
        "TS Spacer / Clear"						    => array("setting" => "Spacer",                 "base" => "TS-VCSC-Spacer",                         "file" => "spacer",            			"group" => "Other",         "type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "1.0.0",    "retired" => "",    "tags" => "",   "link" => ""),
        "TS Almost Anything Slider"					=> array("setting" => "AnySlider",    		    "base" => "TS_VCSC_Anything_Slider",                "file" => "anyslider",  				"group" => "Other",         "type" => "class",			"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "2.6.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/anything-slider/"),
        "TS Almost Anything Grid"					=> array("setting" => "AnyGrid",    		    "base" => "TS_VCSC_Anything_Grid",                  "file" => "anygrid",  				    "group" => "Other",         "type" => "class",			"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "4.1.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/almost-anything-grid/"),
        "TS Animations Frame"					    => array("setting" => "Animations",    		    "base" => "TS_VCSC_Animation_Frame",                "file" => "animations",  				"group" => "Other",         "type" => "class",			"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "2.5.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/animation-frame/"),        
        "TS Icon Wall"                              => array("setting" => "IconWall",    		    "base" => "TS_VCSC_Icon_Wall_Container",            "file" => "iconwall",                   "group" => "Other",         "type" => "class",			"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "3.4.4",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/icon-wall/"),        
        "TS Conditional Output"                     => array("setting" => "TimeSensitive",          "base" => "TS_VCSC_TimeSensitive_Frame",            "file" => "timesensitive",              "group" => "Other",         "type" => "class",			"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "4.2.0",    "retired" => "",    "tags" => "",   "link" => ""),
        "TS Sticky Content Block"                   => array("setting" => "FixedContent",           "base" => "TS_VCSC_FixedContent_Block",             "file" => "fixed_content",              "group" => "Other",         "type" => "class",			"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "5.0.0",  "children" => "0",      "introduced" => "5.2.5",    "retired" => "",    "tags" => "",   "link" => ""),
        "TS Loan Calculator"					    => array("setting" => "LoanCalculator",         "base" => "TS_VCSC_Loan_Calculator",                "file" => "loancalculator",             "group" => "Other",         "type" => "class",		    "default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "5.2.2",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/loan-calculator/"),
        // BETA Elements
        "TS Fancy Tabs (BETA)"					    => array("setting" => "FancyTabs",    		    "base" => "TS_VCSC_Fancy_Tabs_Container",           "file" => "fancytabs",                  "group" => "BETA",          "type" => "class",			"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "4.3.0",  "children" => "0",      "introduced" => "3.3.0",    "retired" => "",    "tags" => "",   "link" => "http://www.composium.krautcoding.com/fancy-tabs/"),
        // Deprecated Elements
        "TS Content Flip (Deprecated)"              => array("setting" => "ContentFlip",            "base" => "TS-VCSC-Content-Flip",                   "file" => "content_flip",      			"group" => "Other",         "type" => "internal",		"default" => "false",		"active" => "false",    "deprecated" => "true",         "required" => "",       "children" => "0",      "introduced" => "1.0.0",    "retired" => "5.1.0",    "tags" => "",   "link" => ""),
        "TS Google Maps (Deprecated)"			    => array("setting" => "GoogleMaps",             "base" => "TS-VCSC-Google-Maps",                    "file" => "google_maps",                "group" => "Google",       	"type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "true",         "required" => "",       "children" => "0",      "introduced" => "1.3.0",    "retired" => "4.0.0",    "tags" => "",   "link" => ""),
        "TS Icon Box (Deprecated)"				    => array("setting" => "IconBoxOld",             "base" => "TS-VCSC-Icon-Box",                       "file" => "icon_box",          			"group" => "Other",         "type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "true",         "required" => "",       "children" => "0",      "introduced" => "1.0.0",    "retired" => "2.2.0",    "tags" => "",   "link" => ""),
        "TS Isotope Timeline (Deprecated)"		    => array("setting" => "Timeline",        	    "base" => "TS_VCSC_Timeline_Container",             "file" => "timeline_isotope",           "group" => "Timelines",     "type" => "class",			"default" => "false",		"active" => "false",	"deprecated" => "true",         "required" => "",       "children" => "0",      "introduced" => "2.3.0",    "retired" => "3.1.0",    "tags" => "",   "link" => ""),
        "TS Lightbox Gallery (Deprecated)"		    => array("setting" => "LightboxGalleryOld",     "base" => "TS-VCSC-Lightbox-Gallery",               "file" => "lightbox_gallery_old",       "group" => "Media",  		"type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "true",         "required" => "",       "children" => "0",      "introduced" => "1.0.0",    "retired" => "2.3.0",    "tags" => "",   "link" => ""),
        "TS Meet The Team (Deprecated)"			    => array("setting" => "MeetTeamOld",            "base" => "TS-VCSC-Meet-Team",                      "file" => "meet_team",         			"group" => "Other",         "type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "true",         "required" => "",       "children" => "0",      "introduced" => "1.0.0",    "retired" => "2.0.0",    "tags" => "",   "link" => ""),
        "TS Processes (Deprecated)"                 => array("setting" => "TimelineOld",            "base" => "TS-VCSC-Timeline",                       "file" => "timeline",          			"group" => "Timelines",     "type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "true",         "required" => "",       "children" => "0",      "introduced" => "1.0.0",    "retired" => "5.0.0",    "tags" => "",   "link" => ""),        
        "TS Row Center Frame (Deprecated)"          => array("setting" => "RowCenter",    		    "base" => "TS_VCSC_RowCenter_Frame",                "file" => "rowcenter",                  "group" => "Other",         "type" => "class",			"default" => "false",		"active" => "false",    "deprecated" => "true",         "required" => "",       "children" => "0",      "introduced" => "3.3.3",    "retired" => "5.0.0",    "tags" => "",   "link" => ""), 
        "TS Single Teammate (Deprecated)"		    => array("setting" => "TeammateOld",            "base" => "TS-VCSC-Team-Mates",                     "file" => "teammates_old",         		"group" => "Other",         "type" => "class",			"default" => "false",		"active" => "false",	"deprecated" => "true",         "required" => "",       "children" => "0",      "introduced" => "2.0.0",    "retired" => "2.2.0",    "tags" => "",   "link" => ""),
        "TS Title Ticker (Deprecated)"              => array("setting" => "TitleTicker",            "base" => "TS_VCSC_Title_Ticker",                   "file" => "title_ticker",               "group" => "Titles",        "type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "true",         "required" => "",       "children" => "0",      "introduced" => "3.0.0",    "retired" => "5.0.0",    "tags" => "",   "link" => ""),        
        "TS YouTube Background (Deprecated)"        => array("setting" => "Background",             "base" => "TS-VCSC-YouTube-Background",             "file" => "background",                 "group" => "Media",         "type" => "internal",		"default" => "false",		"active" => "false",	"deprecated" => "true",         "required" => "",       "children" => "0",      "introduced" => "1.2.0",    "retired" => "3.0.0",    "tags" => "",   "link" => ""),
        // 3rd Party Elements
        "GoPricing Table"						    => array("setting" => "GoPricing",              "base" => "go_pricing",                             "file" => "gopricing",                  "group" => "Plugins",       "type" => "external",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "1.3.0",    "retired" => "",        "tags" => "",   "link" => ""),
        "QuForm"								    => array("setting" => "Quform",                 "base" => $this->TS_VCSC_QuFormReleaseTypeBase,     "file" => "quform",                     "group" => "Plugins",       "type" => "external",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "2.0.0",    "retired" => "",        "tags" => "",   "link" => ""), 
        "Real 3D FlipBook"                          => array("setting" => "Real3DFlipbook",         "base" => "real3dflipbook",                         "file" => "real3dflipbook",             "group" => "Plugins",       "type" => "external",		"default" => "false",		"active" => "false",	"deprecated" => "false",        "required" => "",       "children" => "0",      "introduced" => "3.4.0",    "retired" => "",        "tags" => "",   "link" => ""),
    );

    
    // Container Child Elements
    // ------------------------
    $this->TS_VCSC_Visual_Composer_Children = array(        
        "TS Circle Steps Item"                      => array("parent" => "CircleSteps",             "base" => "TS_VCSC_Circle_Steps_Item",              "file" => "",                           "group" => "Other",         "type" => "class",			"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",      "introduced" => "4.0.0",    "retired" => ""),
        "TS Timeline Event"                         => array("parent" => "MediaTimeline",           "base" => "TS_VCSC_Timeline_CSS_Break",             "file" => "",                           "group" => "Other",         "type" => "class",			"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",      "introduced" => "5.0.0",    "retired" => ""),
        "TS Timeline Break"                         => array("parent" => "MediaTimeline",           "base" => "TS_VCSC_Timeline_CSS_Event",             "file" => "",                           "group" => "Other",         "type" => "class",			"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",      "introduced" => "5.0.0",    "retired" => ""),
        "TS Single Tab (BETA)"                      => array("parent" => "FancyTabs",               "base" => "TS_VCSC_Fancy_Tabs_Single",              "file" => "",                           "group" => "BETA",          "type" => "class",			"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",      "introduced" => "3.3.0",    "retired" => ""),
        "TS Figure Navigation Item"                 => array("parent" => "FigureNavigation",        "base" => "TS_VCSC_Figure_Navigation_Item",         "file" => "",                           "group" => "Buttons",       "type" => "class",			"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",      "introduced" => "2.6.5",    "retired" => ""),
        "TS Google Maps Marker"                     => array("parent" => "GoogleMapsPlus",          "base" => "TS_VCSC_GoogleMapsPlus_Marker",          "file" => "",                           "group" => "Google",        "type" => "class",			"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",      "introduced" => "4.0.0",    "retired" => ""),
        "TS Google Maps Overlay"                    => array("parent" => "GoogleMapsPlus",          "base" => "TS_VCSC_GoogleMapsPlus_Overlay",         "file" => "",                           "group" => "Google",        "type" => "class",			"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",      "introduced" => "4.0.0",    "retired" => ""),
        "TS Google Maps Single"                     => array("parent" => "GoogleMapsPlus",          "base" => "TS_VCSC_GoogleMapsPlus_Single",          "file" => "",                           "group" => "Google",        "type" => "class",			"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",      "introduced" => "4.1.0",    "retired" => ""),
        "TS Horizontal Steps Item"                  => array("parent" => "HorizontalSteps",         "base" => "TS_VCSC_Horizontal_Steps_Item",          "file" => "",                           "group" => "Other",         "type" => "class",			"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",      "introduced" => "1.0.0",    "retired" => ""),
        "TS Icon Wall Item"                         => array("parent" => "IconWall",                "base" => "TS_VCSC_Icon_Wall_Item",                 "file" => "",                           "group" => "Other",         "type" => "class",			"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",      "introduced" => "3.4.4",    "retired" => ""),
        "TS Single Hotspot"                         => array("parent" => "ImageHotspot",            "base" => "TS_VCSC_Image_Hotspot_Single",           "file" => "",                           "group" => "Media",         "type" => "class",			"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",      "introduced" => "2.6.4",    "retired" => ""),
        "TS iPresenter Item"                        => array("parent" => "iPresenter",              "base" => "TS_VCSC_iPresenter_Item",                "file" => "",                           "group" => "Other",         "type" => "class",			"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",      "introduced" => "2.7.2",    "retired" => ""),
        "TS SlitSlider Item"                        => array("parent" => "SlitSlider",              "base" => "TS_VCSC_SlitSlider_Item",                "file" => "",                           "group" => "Other",         "type" => "class",			"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",      "introduced" => "3.4.0",    "retired" => ""),        
        "TS Process Lines Item"                     => array("parent" => "ProcessLines",            "base" => "TS_VCSC_ProcessLines_Item",              "file" => "",                           "group" => "Other",         "type" => "class",			"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",      "introduced" => "1.0.0",    "retired" => ""),        
        "TS Teaser Block Slider"                    => array("parent" => "TeaserBlock",             "base" => "TS_VCSC_Teaser_Block_Slider_Custom",     "file" => "",                           "group" => "Titles",        "type" => "class",			"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",      "introduced" => "2.3.0",    "retired" => ""),
        "TS Teaser Block Slide"                     => array("parent" => "TeaserBlock",             "base" => "TS_VCSC_Teaser_Block_Single",            "file" => "",                           "group" => "Titles",        "type" => "class",			"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",      "introduced" => "2.3.0",    "retired" => ""),
        "TS Inspired Table Item"                    => array("parent" => "PricingInspired",         "base" => "TS_VCSC_InspiredPricing_Item",           "file" => "",                           "group" => "Other",         "type" => "class",			"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",      "introduced" => "4.3.0",    "retired" => ""),
        "TS Inspired Table Single"                  => array("parent" => "PricingInspired",         "base" => "TS_VCSC_InspiredPricing_Single",         "file" => "",                           "group" => "Other",         "type" => "class",			"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",      "introduced" => "4.3.0",    "retired" => ""),
        "TS Timeline Item (Deprecated)"             => array("parent" => "Timeline",                "base" => "TS_VCSC_Timeline_Single",                "file" => "",                           "group" => "Other",         "type" => "class",			"default" => "false",		"active" => "false",    "deprecated" => "true",         "required" => "",      "introduced" => "2.3.0",    "retired" => "3.1.0"),
        "TS Timeline Break (Deprecated)"            => array("parent" => "Timeline",                "base" => "TS_VCSC_Timeline_Break",                 "file" => "",                           "group" => "Other",         "type" => "class",			"default" => "false",		"active" => "false",    "deprecated" => "true",         "required" => "",      "introduced" => "2.3.0",    "retired" => "3.1.0"),
    );
    

    // Post Type Elements
    // ------------------
    $this->TS_VCSC_Visual_Composer_Types = array(
        "TS Skillset Bars"                          => array("posttype" => "ts_skillsets",          "base" => "TS_VCSC_Skill_Sets_Standalone",          "file" => "",                           "group" => "Post Types",    "type" => "class",			"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",      "introduced" => "2.2.0",    "retired" => ""),
        "TS Skillset Raphael"                       => array("posttype" => "ts_skillsets",          "base" => "TS_VCSC_Skill_Sets_Raphael",             "file" => "",                           "group" => "Post Types",    "type" => "class",			"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",      "introduced" => "2.6.6",    "retired" => ""),
        "TS Single Teammate"                        => array("posttype" => "ts_team",               "base" => "TS_VCSC_Team_Mates_Standalone",          "file" => "",                           "group" => "Post Types",    "type" => "class",			"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",      "introduced" => "2.0.0",    "retired" => ""),
        "TS Teammate Slide"                         => array("posttype" => "ts_team",               "base" => "TS_VCSC_Team_Mates_Single",              "file" => "",                           "group" => "Post Types",    "type" => "class",			"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",      "introduced" => "2.2.0",    "retired" => ""),
        "TS Teammates Slider 1"                     => array("posttype" => "ts_team",               "base" => "TS_VCSC_Team_Mates_Slider_Custom",       "file" => "",                           "group" => "Post Types",    "type" => "class",			"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",      "introduced" => "2.2.0",    "retired" => ""),
        "TS Teammates Slider 2"                     => array("posttype" => "ts_team",               "base" => "TS_VCSC_Team_Mates_Slider_Category",     "file" => "",                           "group" => "Post Types",    "type" => "class",			"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",      "introduced" => "2.2.0",    "retired" => ""),
        "TS Teampage Section"                       => array("posttype" => "ts_team",               "base" => "TS_VCSC_Team_Page_Elements",             "file" => "",                           "group" => "Post Types",    "type" => "class",			"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",      "introduced" => "2.6.2",    "retired" => ""),
        "TS Single Testimonial"                     => array("posttype" => "ts_testimonials",       "base" => "TS_VCSC_Testimonial_Standalone",         "file" => "",                           "group" => "Post Types",    "type" => "class",			"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",      "introduced" => "2.1.0",    "retired" => ""),
        "TS Testimonial Slide"                      => array("posttype" => "ts_testimonials",       "base" => "TS_VCSC_Testimonial_Single",             "file" => "",                           "group" => "Post Types",    "type" => "class",			"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",      "introduced" => "2.1.0",    "retired" => ""),
        "TS Testimonials Slider 1"                  => array("posttype" => "ts_testimonials",       "base" => "TS_VCSC_Testimonial_Slider_Custom",      "file" => "",                           "group" => "Post Types",    "type" => "class",			"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",      "introduced" => "2.1.0",    "retired" => ""),
        "TS Testimonials Slider 2"                  => array("posttype" => "ts_testimonials",       "base" => "TS_VCSC_Testimonial_Slider_Category",    "file" => "",                           "group" => "Post Types",    "type" => "class",			"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",      "introduced" => "2.1.0",    "retired" => ""),
        "TS Testimonial Form"                       => array("posttype" => "ts_testimonials",       "base" => "TS_VCSC_Testimonial_Frontend_Form",      "file" => "",                           "group" => "Post Types",    "type" => "class",			"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",      "introduced" => "4.0.0",    "retired" => ""),
        "TS CSS Media Timeline"                     => array("posttype" => "ts_timeline",           "base" => "TS_VCSC_Timeline_CSS_Container",         "file" => "",                           "group" => "Post Types",    "type" => "class",			"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",      "introduced" => "3.1.0",    "retired" => ""),
        "TS Timeline Section"                       => array("posttype" => "ts_timeline",           "base" => "TS_VCSC_Timeline_CSS_Section",           "file" => "",                           "group" => "Post Types",    "type" => "class",			"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",      "introduced" => "3.1.0",    "retired" => ""),
        "TS Logo Layouts"                           => array("posttype" => "ts_logos",              "base" => "TS_VCSC_Logo_Layouts_Category",          "file" => "",                           "group" => "Post Types",    "type" => "class",			"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",      "introduced" => "4.0.0",    "retired" => ""),
        "TS VC Template (BETA)"                     => array("posttype" => "ts_widgets",            "base" => "TS_VCSC_VCWidget_Output",                "file" => "",                           "group" => "Post Types",    "type" => "class",			"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",      "introduced" => "4.2.0",    "retired" => ""),
    );
    
    
    // Extra Elements
    // --------------
    $this->TS_VCSC_Visual_Composer_Extra = array(
        // Enlighter Elements
        "TS EnlighterJS Single Code"                => array("feature" => "Enlighter",              "base" => "TS_EnlighterJS_Snippet_Single",          "file" => "",                           "group" => "Extra",         "type" => "class",			"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",      "introduced" => "4.0.0",    "retired" => ""),
        "TS EnlighterJS Group Code"                 => array("feature" => "Enlighter",              "base" => "TS_EnlighterJS_Snippet_Group",           "file" => "",                           "group" => "Extra",         "type" => "class",			"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",      "introduced" => "4.0.0",    "retired" => ""),
        "TS EnlighterJS Group Container"            => array("feature" => "Enlighter",              "base" => "TS_EnlighterJS_Snippet_Container",       "file" => "",                           "group" => "Extra",         "type" => "class",			"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",      "introduced" => "4.0.0",    "retired" => ""),
        // Navigator Elements
        "TS SinglePage Navigator"                   => array("feature" => "Navigator",              "base" => "TS_VCSC_SinglePage_Container",           "file" => "",                           "group" => "Extra",         "type" => "class",			"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",      "introduced" => "3.3.3",    "retired" => ""),
        "TS Single Menu Item"                       => array("feature" => "Navigator",              "base" => "TS_VCSC_SinglePage_Item",                "file" => "",                           "group" => "Extra",         "type" => "class",			"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",      "introduced" => "3.3.3",    "retired" => ""),
        "TS ToTop Menu Item"                        => array("feature" => "Navigator",              "base" => "TS_VCSC_SinglePage_ToTop",               "file" => "",                           "group" => "Extra",         "type" => "class",			"default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",      "introduced" => "3.3.3",    "retired" => ""),
    );
    
    
    // Demo Elements
    // -------------
    $this->TS_VCSC_Visual_Composer_Demos = array(
        // Demo Elements
        "TS Icon Font Preview"                      => array("setting" => "IconFonts",              "base" => "TS_VCSC_Icon_Preview",                   "file" => "demo_iconfonts",             "group" => "Demos",         "type" => "internal",       "default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",      "introduced" => "2.2.4",    "retired" => ""),        
        "TS CSS3 Animations"                        => array("setting" => "Animations",             "base" => "TS_VCSC_Icon_Animations",                "file" => "demo_animations",            "group" => "Demos",         "type" => "internal",       "default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",      "introduced" => "2.2.4",    "retired" => ""),
        "TS Preloader Preview"                      => array("setting" => "Preloaders",             "base" => "TS_VCSC_Preloaders",                     "file" => "demo_preloaders",            "group" => "Demos",         "type" => "internal",       "default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",      "introduced" => "5.1.1",    "retired" => ""),
        "TS System Information"                     => array("setting" => "SystemInfo",             "base" => "TS_VCSC_System_Information",             "file" => "demo_system",                "group" => "Demos",         "type" => "internal",       "default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",      "introduced" => "2.2.4",    "retired" => ""),        
        "TS PHP Info Summary"                       => array("setting" => "PHPInfo",                "base" => "TS_VCSC_PHPInfo_Summary",                "file" => "demo_phpinfo",               "group" => "Demos",         "type" => "internal",       "default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",      "introduced" => "5.0.0",    "retired" => ""),
        "TS Page Content Export"                    => array("setting" => "ContentExport",          "base" => "TS_VCSC_Content_Export",                 "file" => "demo_export",                "group" => "Demos",         "type" => "internal",       "default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",      "introduced" => "5.1.0",    "retired" => ""),
        "TS Parameter Showcase"                     => array("setting" => "Parameters",             "base" => "TS_VCSC_Parameter_Showcase",             "file" => "demo_parameters",            "group" => "Demos",         "type" => "internal",       "default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",      "introduced" => "5.0.0",    "retired" => ""),
        "Other Shortcodes (No Elements)"            => array("setting" => "Shortcodes",             "base" => "",                                       "file" => "demo_others",                "group" => "Demos",         "type" => "internal",       "default" => "false",		"active" => "false",    "deprecated" => "false",        "required" => "",      "introduced" => "2.2.4",    "retired" => ""),
    );
    
    
    // WooCommerce Elements
    // --------------------
    $this->TS_VCSC_WooCommerce_Elements = array(
        "Basic Products Slider"				        => array("setting" => "SliderBasic",            "base" => "TS_VCSC_WooCommerce_Slider_Basic",       "file" => "custom_slider",             	"group" => "WooCommerce",   "type" => "class",	        "default" => "false",		"active" => "false",    "deprecated" => "false",      "introduced" => "2.5.0",    "retired" => ""),
        "Basic Products Isotope Grid"               => array("setting" => "GridBasic",              "base" => "TS_VCSC_WooCommerce_Grid_Basic",         "file" => "custom_grid",             	"group" => "WooCommerce",   "type" => "class",	        "default" => "false",		"active" => "false",    "deprecated" => "false",      "introduced" => "2.6.3",    "retired" => ""),
        "Basic Products Image Grid"                 => array("setting" => "GridImage",              "base" => "TS_VCSC_WooCommerce_ImageGrid_Basic",    "file" => "custom_image",             	"group" => "WooCommerce",   "type" => "class",	        "default" => "false",		"active" => "false",    "deprecated" => "false",      "introduced" => "3.0.0",    "retired" => ""),
        "Basic Products Ticker"				        => array("setting" => "TickerBasic",            "base" => "TS_VCSC_WooCommerce_Ticker_Basic",       "file" => "custom_ticker",             	"group" => "WooCommerce",   "type" => "class",	        "default" => "false",		"active" => "false",    "deprecated" => "false",      "introduced" => "2.6.3",    "retired" => ""),
        //"Basic Product Statistics"                => array("setting" => "ProductStats",           "base" => "TS_VCSC_WooCommerce_Product_Statistics", "file" => "custom_statistics",          "group" => "WooCommerce",   "type" => "class",	        "default" => "false",		"active" => "false",    "deprecated" => "false",      "introduced" => "5.1.7",    "retired" => ""),
        "Single Product Rating"				        => array("setting" => "RatingBasic",            "base" => "TS_VCSC_WooCommerce_Rating_Basic",       "file" => "custom_rating",             	"group" => "WooCommerce",   "type" => "class",	        "default" => "false",		"active" => "false",    "deprecated" => "false",      "introduced" => "2.6.3",    "retired" => ""),
    );
    
    
    // bbPress Elements
    // ----------------
    $this->TS_VCSC_bbPress_Elements = array(
        "Forum Index"						        => array("setting" => "ForumIndex",             "base" => "bbp-forum-index",                        "file" => "forumindex",                 "group" => "bbPress",       "type" => "internal",	    "default" => "false",		"active" => "false",    "deprecated" => "false",      "introduced" => "2.7.0",    "retired" => ""),
        "Forum Form"						        => array("setting" => "ForumForm",              "base" => "bbp-forum-form",                         "file" => "forumform",                  "group" => "bbPress",       "type" => "internal",	    "default" => "false",		"active" => "false",    "deprecated" => "false",      "introduced" => "2.7.0",    "retired" => ""),
        "Single Forums Topics"                      => array("setting" => "ForumSingle",            "base" => "bbp-single-forum",                       "file" => "forumsingle",                "group" => "bbPress",       "type" => "internal",	    "default" => "false",		"active" => "false",    "deprecated" => "false",      "introduced" => "2.7.0",    "retired" => ""),
        "Topic Index"						        => array("setting" => "TopicIndex",             "base" => "bbp-topic-index",                        "file" => "topicindex",                 "group" => "bbPress",       "type" => "internal",	    "default" => "false",		"active" => "false",    "deprecated" => "false",      "introduced" => "2.7.0",    "retired" => ""),
        "Topic Form"						        => array("setting" => "TopicForm",              "base" => "bbp-topic-form",                         "file" => "topicform",                  "group" => "bbPress",       "type" => "internal",	    "default" => "false",		"active" => "false",    "deprecated" => "false",      "introduced" => "2.7.0",    "retired" => ""),
        "Single Topic"						        => array("setting" => "TopicSingle",            "base" => "bbp-single-topic",                       "file" => "topicsingle",                "group" => "bbPress",       "type" => "internal",	    "default" => "false",		"active" => "false",    "deprecated" => "false",      "introduced" => "2.7.0",    "retired" => ""),
        "Reply Form"						        => array("setting" => "ReplyForm",              "base" => "bbp-reply-form",                         "file" => "replyform",                  "group" => "bbPress",       "type" => "internal",	    "default" => "false",		"active" => "false",    "deprecated" => "false",      "introduced" => "2.7.0",    "retired" => ""),
        "Single Reply"						        => array("setting" => "ReplySingle",            "base" => "bbp-single-reply",                       "file" => "replysingle",                "group" => "bbPress",       "type" => "internal",	    "default" => "false",		"active" => "false",    "deprecated" => "false",      "introduced" => "2.7.0",    "retired" => ""),
        "Topic Tags"						        => array("setting" => "TagsTopic",              "base" => "bbp-topic-tags",                         "file" => "tagstopic",                  "group" => "bbPress",       "type" => "internal",	    "default" => "false",		"active" => "false",    "deprecated" => "false",      "introduced" => "2.7.0",    "retired" => ""),
        "Single Tags"						        => array("setting" => "TagsSingle",             "base" => "bbp-single-tag",                         "file" => "tagssingle",                 "group" => "bbPress",       "type" => "internal",	    "default" => "false",		"active" => "false",    "deprecated" => "false",      "introduced" => "2.7.0",    "retired" => ""),
        "Single View"						        => array("setting" => "ViewSingle",             "base" => "bbp-single-view",                        "file" => "viewsingle",                 "group" => "bbPress",       "type" => "internal",	    "default" => "false",		"active" => "false",    "deprecated" => "false",      "introduced" => "2.7.0",    "retired" => ""),
        "Search Form"						        => array("setting" => "SearchForm",             "base" => "bbp-search",                             "file" => "searchform",                 "group" => "bbPress",       "type" => "internal",	    "default" => "false",		"active" => "false",    "deprecated" => "false",      "introduced" => "2.7.0",    "retired" => ""),
        "Search Template"                           => array("setting" => "SearchTemplate",         "base" => "bbp-search-form",                        "file" => "searchtemplate",             "group" => "bbPress",       "type" => "internal",	    "default" => "false",		"active" => "false",    "deprecated" => "false",      "introduced" => "2.7.0",    "retired" => ""),
        "Login Screen"                              => array("setting" => "AccountLogin",           "base" => "bbp-login",                              "file" => "accountlogin",               "group" => "bbPress",       "type" => "internal",	    "default" => "false",		"active" => "false",    "deprecated" => "false",      "introduced" => "2.7.0",    "retired" => ""),
        "Register Screen"                           => array("setting" => "AccountRegister",        "base" => "bbp-register",                           "file" => "accountregister",            "group" => "bbPress",       "type" => "internal",	    "default" => "false",		"active" => "false",    "deprecated" => "false",      "introduced" => "2.7.0",    "retired" => ""),
        "Lost Password Screen"                      => array("setting" => "AccountPassword",        "base" => "bbp-lost-pass",                          "file" => "accountpassword",            "group" => "bbPress",       "type" => "internal",	    "default" => "false",		"active" => "false",    "deprecated" => "false",      "introduced" => "2.7.0",    "retired" => ""),
        "Forum Statistics"                          => array("setting" => "ForumStatistics",        "base" => "bbp-stats",                              "file" => "forumstatistics",            "group" => "bbPress",       "type" => "internal",	    "default" => "false",		"active" => "false",    "deprecated" => "false",      "introduced" => "2.7.0",    "retired" => ""),
    );
    
    
    // Deprecated to Replacement
    // -------------------------
    $this->TS_VCSC_Visual_Composer_Migrate = array(
        "TS-VCSC-Content-Flip"                      => "Replaced By: TS Panel Flip (Group: Other).",
        "TS-VCSC-Google-Maps"                       => "Replaced By: TS Google Maps PLUS (Group: Google).",
        "TS-VCSC-Icon-Box"                          => "Replaced By: TS Icon Text Box (Group: Other).",
        "TS_VCSC_Timeline_Container"                => "Replaced By: TS CSS Media Timeline (Group: Timelines).",
        "TS-VCSC-Lightbox-Gallery"                  => "Replaced By: TS Image Gallery (Group: Media).",
        "TS-VCSC-Meet-Team"                         => "Replaced By: Post Type 'VC Team' (Tab: Custom Post Types).",
        "TS-VCSC-Timeline"                          => "Replaced By: TS Process Lines (Group: Timeline).",
        "TS_VCSC_RowCenter_Frame"                   => "No replacement; feature now provided by WP Bakery Page Builder itself.",
        "TS-VCSC-Team-Mates"                        => "Replaced By: Post Type 'VC Team' (Tab: Custom Post Types).",
        "TS_VCSC_Title_Ticker"                      => "Replaced By: TS Title Morphed (Group: Title).",
        "TS-VCSC-YouTube-Background"                => "Replaced By: TS Page Background (Group: Media).",
    );
    
    
    // Setting Parameters
    // ------------------
    $this->TS_VCSC_ComposerParameters = array(
        "Post Type Paramater"                       => array("file" => "standardpost"),
        "Custom Post Type Parameter"                => array("file" => "custompost"),
        "CSS3 Animation Parameter"                  => array("file" => "animations"),
        "Separator Parameter"            		    => array("file" => "separator"),
        "Messenger Parameter"                       => array("file" => "messenger"),
        "Video Select Parameter"                    => array("file" => "videoselect"),
        "Audio Select Parameter"                    => array("file" => "audioselect"),
        "Icons Panel Parameter"                     => array("file" => "iconspanel"),
        "Image Select Parameter"                    => array("file" => "imageselect"),        
        "Background Panel Parameter"                => array("file" => "backgroundpanel"),
        "Map Marker Parameter"                      => array("file" => "markerpanel"),
        "Switch Parameter"                          => array("file" => "switch"),
        "NoUiSlider Parameter"                      => array("file" => "nouislider"),
        "Image Hotspot Parameter"                   => array("file" => "imagehotspot"),
        "Google Fonts Parameter"                    => array("file" => "googlefonts"),
        "Hidden Input Parameter"                    => array("file" => "hiddeninput"),
        "Hidden Textarea Parameter"                 => array("file" => "hiddentextarea"),
        "Date / Time Picker Parameter"              => array("file" => "datetimepicker"),   
        "Advanced Setting Parameter"                => array("file" => "advancedsetting"),
        "Advanced Gradient Parameter"               => array("file" => "advancedgradient"),
        "Social Networks Parameter"                 => array("file" => "socialnetworks"),
        "Device Type Selectors"                     => array("file" => "devicetypes"),
        "Screen Size Selectors"                     => array("file" => "screensizes"),
        "ID / Number Auto-Generator Parameter"      => array("file" => "autogenerate"),
        "User Roles Parameter"                      => array("file" => "userroles"),
        "Viewport Animation Offset"                 => array("file" => "viewportoffset"),
        "Advanced Link Parameter"                   => array("file" => "advancedlinks"),
        "Live Preview Parameter"                    => array("file" => "livepreview"),
        "Tag Input Parameter"                       => array("file" => "tageditor"),
        "WooCommerce Parameters"                    => array("file" => "woocommerce"),
        "bbPress Parameters"              		    => array("file" => "bbpress"),
        "WYSIWYG Editor Parameter"                  => array("file" => "wysiwyg"),
        "Conditionals Parameter"                    => array("file" => "conditionals"),
        "Fontsize Generator Parameter"              => array("file" => "fontsize"),
    );
    
    
    // Post Type Names
    // ---------------
    $this->TS_VCSC_PostTypeMenuNames_Default = array(
        "ts_widgets"                                => "CP Templates",        
        "ts_timeline"                               => "CP Timelines",
        "ts_team"                                   => "CP Team",
        "ts_testimonials"                           => "CP Testimonials",
        "ts_skillsets"                              => "CP Skillsets",
        "ts_logos"                                  => "CP Logos",
        "ts_downtime"                               => "CP Downpages",
    );
    
    
    // Post Type Options
    // -----------------
    $this->TS_VCSC_PostTypeOptionNames_Default = array(
        "ts_widgets"                                => "ts_vcsc_extend_settings_customWidgets",        
        "ts_timeline"                               => "ts_vcsc_extend_settings_customTimelines",
        "ts_team"                                   => "ts_vcsc_extend_settings_customTeam",
        "ts_testimonials"                           => "ts_vcsc_extend_settings_customTestimonial",
        "ts_skillsets"                              => "ts_vcsc_extend_settings_customSkillset",
        "ts_logos"                                  => "ts_vcsc_extend_settings_customLogo",
        "ts_downtime"                               => "ts_vcsc_extend_settings_allowDowntimeManager",
    );
    
    
    // Other Plublic Arrays
    // --------------------
    $this->TS_VCSC_TeamPageBuilder_Included = array (
        // Extensions Elements
        'TS_VCSC_Team_Page_Featured',
        'TS_VCSC_Team_Page_NameTitle',
        'TS_VCSC_Team_Page_Contact',
        'TS_VCSC_Team_Page_Social',
        'TS_VCSC_Team_Page_Description',
        'TS_VCSC_Team_Page_Opening',
        'TS_VCSC_Team_Page_Download',
        'TS_VCSC_Team_Page_Skills',
        'TS_VCSC_Star_Rating',
        'TS-VCSC-Icon-Counter',
        'TS-VCSC-Circliful',
        'TS-VCSC-Icon-Title',
        'TS_VCSC_Skill_Sets_Standalone',
        'TS-VCSC-Divider',
        'TS-VCSC-Spacer',
        'TS_VCSC_Spacer',
        'TS-VCSC-QRCode',
        // Original VC Elements
        'vc_column_text',
        'vc_toggle',
        'vc_message',
        'vc_separator',
        'vc_text_separator',
    );
    
    $this->TS_VCSC_AnyLayout_Excluded = array (
        // Extension Elements
        'TS_VCSC_FixedContent_Block',
        'TS_VCSC_Anything_Slider',
        'TS_VCSC_Anything_Grid',
        'TS_VCSC_Animation_Frame',
        'TS_VCSC_Horizontal_Steps_Container',
        'TS_VCSC_Circle_Steps_Container',
        'TS_VCSC_Timeline_Container',
        'TS_VCSC_Timeline_Single',
        'TS_VCSC_Timeline_Break',
        'TS_VCSC_Team_Mates_Single',
        'TS_VCSC_Team_Mates_Slider_Custom',
        'TS_VCSC_Team_Mates_Slider_Category',
        'TS_VCSC_Testimonial_Single',
        'TS_VCSC_Testimonial_Slider_Custom',
        'TS_VCSC_Testimonial_Slider_Category',
        'TS_VCSC_Teaser_Block_Single',
        'TS_VCSC_Teaser_Block_Slider_Custom',
        'TS_VCSC_Logo_Single',
        'TS_VCSC_Logo_Slider_Custom',
        'TS_VCSC_Logo_Slider_Category',
        'TS_VCSC_Posts_Grid_Standalone',
        'TS_VCSC_Posts_Slider_Standalone',
        'TS-VCSC-Image-Full',
        'TS_VCSC_Image_Full',
        'TS-VCSC-YouTube-Background',
        'TS_VCSC_YouTube_Background',
        'TS-VCSC-Google-Charts',
        'TS_VCSC_Google_Charts',
        'TS-VCSC-Google-Maps',
        'TS_VCSC_Google_Maps',
        'TS-VCSC-Google-Trends',
        'TS_VCSC_Google_Trends',
        'TS-VCSC-Google-Docs',
        'TS_VCSC_Google_Docs',
        'TS-VCSC-Textillate',
        'TS_VCSC_Textillate',
        'TS-VCSC-Icon-Title',
        'TS_VCSC_Icon_Title',
        'TS-VCSC-Timeline',
        'TS_VCSC_Timeline',
        'TS-VCSC-Divider',
        'TS_VCSC_Divider',
        'TS-VCSC-Spacer',
        'TS_VCSC_Spacer',
        // Original VC Elements
        'wpb_column',
        'vc_row',
        'vc_row_inner',
        'vc_section',
        'vc_gallery',
        'vc_images_carousel',
        'vc_carousel',
        'vc_posts_slider',
        'vc_accordion',
        'vc_tour',
        'vc_tabs',
        'vc_empty_space',
        'vc_pie',
        // WooCommerce Elements
        'woocommerce_cart',
        'woocommerce_checkout',
        'woocommerce_order_tracking',
        'woocommerce_my_account',
        'add_to_cart',
        'add_to_cart_url',
        'product_page',
        'related_products',
        // Other Elements
        'layerslider',
        'rev_slider',
    );
    
    $this->TS_VCSC_Focus_Excluded = array (
        // Extension Elements
        'TS_VCSC_Element_Focus',
        // Original VC Elements
        'vc_row',
        'vc_accordion',
        'vc_tour',
        'vc_tabs',
        // WooCommerce Elements
        'woocommerce_cart',
        'woocommerce_checkout',
        'woocommerce_order_tracking',
        'woocommerce_my_account',
        'add_to_cart',
        'add_to_cart_url',
        'product_page',
        'related_products',
        // Other Elements
        'layerslider',
        'rev_slider',
    );
?>