<?php $icons = array();
$icons['stmicons']['arrow_forward'] = array("class"=>'arrow_forward',"tags"=>'arrow_forward');
$icons['stmicons']['corporate-case'] = array("class"=>'corporate-case',"tags"=>'corporate-case');
$icons['stmicons']['corporate-mark'] = array("class"=>'corporate-mark',"tags"=>'corporate-mark');
$icons['stmicons']['corporate-specialist'] = array("class"=>'corporate-specialist',"tags"=>'corporate-specialist');
$icons['stmicons']['corporate-solution'] = array("class"=>'corporate-solution',"tags"=>'corporate-solution');
$icons['stmicons']['corporate-investment'] = array("class"=>'corporate-investment',"tags"=>'corporate-investment');
$icons['stmicons']['corporate-roadmap'] = array("class"=>'corporate-roadmap',"tags"=>'corporate-roadmap');
$icons['stmicons']['corporate-consulting'] = array("class"=>'corporate-consulting',"tags"=>'corporate-consulting');
$icons['stmicons']['corporate-boosted-pc'] = array("class"=>'corporate-boosted-pc',"tags"=>'corporate-boosted-pc');
$icons['stmicons']['corporate-support-manager'] = array("class"=>'corporate-support-manager',"tags"=>'corporate-support-manager');
$icons['stmicons']['corporate-doc'] = array("class"=>'corporate-doc',"tags"=>'corporate-doc');
$icons['stmicons']['corporate-chart'] = array("class"=>'corporate-chart',"tags"=>'corporate-chart');
$icons['stmicons']['corporate-mouse'] = array("class"=>'corporate-mouse',"tags"=>'corporate-mouse');