<?php $icons = array();
$icons['stmicons']['dark_agency_call_center'] = array("class"=>'dark_agency_call_center',"tags"=>'dark_agency_call_center');
$icons['stmicons']['dark_agency_comments'] = array("class"=>'dark_agency_comments',"tags"=>'dark_agency_comments');
$icons['stmicons']['dark_agency_devices'] = array("class"=>'dark_agency_devices',"tags"=>'dark_agency_devices');
$icons['stmicons']['dark_agency_graphic'] = array("class"=>'dark_agency_graphic',"tags"=>'dark_agency_graphic');
$icons['stmicons']['dark_agency_graphic2'] = array("class"=>'dark_agency_graphic2',"tags"=>'dark_agency_graphic2');
$icons['stmicons']['dark_agency_magic-wand'] = array("class"=>'dark_agency_magic-wand',"tags"=>'dark_agency_magic-wand');
$icons['stmicons']['dark_agency_notebook'] = array("class"=>'dark_agency_notebook',"tags"=>'dark_agency_notebook');
$icons['stmicons']['dark_agency_pencil'] = array("class"=>'dark_agency_pencil',"tags"=>'dark_agency_pencil');
$icons['stmicons']['dark_agency_rocket'] = array("class"=>'dark_agency_rocket',"tags"=>'dark_agency_rocket');
$icons['stmicons']['dark_agency_target'] = array("class"=>'dark_agency_target',"tags"=>'dark_agency_target');
$icons['stmicons']['cube'] = array("class"=>'cube',"tags"=>'cube');
$icons['stmicons']['levels'] = array("class"=>'levels',"tags"=>'levels');
$icons['stmicons']['smartphone'] = array("class"=>'smartphone',"tags"=>'smartphone');
$icons['stmicons']['video-player'] = array("class"=>'video-player',"tags"=>'video-player');
$icons['stmicons']['message'] = array("class"=>'message',"tags"=>'message');
$icons['stmicons']['address'] = array("class"=>'address',"tags"=>'address');
$icons['stmicons']['phone-call'] = array("class"=>'phone-call',"tags"=>'phone-call');